# Generated by Django 2.2.6 on 2019-11-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='passport',
            new_name='passenger',
        ),
    ]
