# Generated by Django 2.2.6 on 2019-11-02 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0003_remove_airline_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crewmember',
            name='Type',
            field=models.CharField(choices=[('Pilot', 'Pilot'), ('Flight Attendant', 'Flight Attendant')], default='Flight Attendant', max_length=20),
        ),
        migrations.AlterField(
            model_name='crewmember',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
