# Generated by Django 2.2.6 on 2019-11-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0005_passenger_checked_in_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airline',
            name='cost_per_seat',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='image',
            field=models.ImageField(upload_to='gallery'),
        ),
    ]
