# Generated by Django 2.2.6 on 2019-12-13 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airport_app', '0006_auto_20191112_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), (' F', 'Female'), ('O', 'others')], default='M', max_length=1),
        ),
    ]
